# Exercise Set 3 Answers {.unlisted .unnumbered}

1.  Solve the following quadratic equations by factorisation.

    a.  $x^2-28x-60=0$
    b.  $p^2=8p-15$
    c.  $3x^2-14x+8$
    d.  $x^2+10x+25$

    Answers:
    
    a.  We are looking for two factors of 25 with summation equal to 10. Thus, these factors are 5 and 5

    $$
    x^2 + 10x + 25 = (x+5)(x+5) = (x+5)^2
    $$
    So there is a single solution $x=-5$.

    b. Factorise by inspection into the form $(x+a)(x+b)$ where $ab = -60$ and $a + b = -28$
    
    \begin{align*}
    x^2-28x-60 &= 0\\
    (x-30)(x+2) & = 0\\
    \Rightarrow  x=30, -2
    \end{align*}
    
    c. First, put into quadratic form $ax^2 + bx + c = 0$ and then factorise by inspection
    
    \begin{align*}
    p^2 = 8p - 18\\
    p^2 - 8p + 15 &= 0\\
    (p-3)(p-5) &= 0\\
    \Rightarrow p = 3,5
    \end{align*}

    d. We are looking for two factors of $3\times 8 = 24$ with summation equals to -14. These factors are $-12$ and $-2$
    \begin{align*}
    3x^2 - 14x + 8 &= 3x^2 - 12x - 2x + 8\\
    &= 3x(x-4) - 2(x-4) = (x-4)(3x-2)
    \end{align*}

        
1.  Solve the following quadratic equations, giving results correct to 2 d.p.

    a.  $4x^2+x-3=0$
    b.  $x^2+x=5$
    c.  $x+\frac{1}{x}=5$
    
    Answers:

    These questions require the application of the quadratic formula: for a quadratic which can be put into the form $ax^2 + bx + c = 0$,
    $$
    x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
    $$

    a. $4x^2 + x - 3$
    
    $$
    x = \frac{-1 \pm \sqrt{1^2 - 4\times 4 \times (-3)}}{8}\\
    x = 3.38, -3.63
    $$
    b. First, rearrange $x^2 + x = 5$ as $x^2 + x - 5 =0$, then apply the quadratic formula
    $$
    x = \frac{-1 \pm \sqrt{1^2 - 4\times 1 \times (-5)}}{2}\\
    x = 1.79, -2.79
    $$
    c. First, rearrange $x + \frac{1}{x} = 5$ into $x^2 + 1 - 5 = 0$ and then apply the quadratic formula.
    $$
    x = \frac{5 \pm \sqrt{(-5)^2 - 4\times 1 \times 1}}{2}\\
    x = 4.79, 0.21
    $$
    
    
9.  Solve the following sets of simultaneous equations.

    a.  $3x+4y=7$, $5x+6y=11$
    b.  $2x+y=7$, $x^2-xy=6$
    c.  $x + y=2$, $x^2-xy+y^2 = 1$

    Answers:

    a. Because these simultaneous equations are linear in $x$ and $y$, they can be solved by multiplying the equations and adding or subtracting them to cancel one of $x$ or $y$. Here, they can be solved by multiplying the left equation by 5 and the right equation by 3, then subtracting to cancel the $x$ term:
    $$
    3x+4y = 7,\quad 5x + 6y = 11\\
    15 x + 20y = 35,\quad 15x + 18y = 33\\
    \text{subtracting the right equaltion from the left:}\\
    2y = 2 \Rightarrow y=1,x=1
    $$
    This could also have been solved via direct substitution (e.g., $x = (7-4y)/3$).

    b. 
    $$ 2x + y = 7,\quad x^2 - xy = 6\\
    \Rightarrow y=7-2x \. \text{substitute into right hand equation}\\
    x^2 - x(7-2x) = 6\\
    x^2 - 7x + 2x^2 = 6\\
    3x^2 - 7x - 6 = 0
    $$
    which can now be factorised by inspection to obtain the two solutions for $x$
    $$
    (3x+2)(x-3) = 0\\
    \Rightarrow x = -\frac{2}{3},x = 3
    $$
    The value for $y$ must be calculated for both cases of $x$. It is simplest to use $y = 7 - 2x$. The solutions are:
    $$
    x = -\frac{2}{3},y=\frac{25}{3},\quad\text{and  }\, x = 3, y = 1
    $$

    c. As before, substitute one of $x$ or $y$ using the linear equation
    $$
    x+y = 2, \quad x^2 - xy + y^2 = 1\\
    \Rightarrow x = 2-y,\quad (2-y)^2 - (2-y)y + y^2 = 1\\
    4 - 4y^2 + y^2 - 2y + y^2 + y^2 = 1\\
    y^2 + 2y - 3 = 0\\
    (y+3)(y-1) = 0\\
    y=1, -3
    $$
    and again, we must give $x$ for both cases. The two solutions are
    $$
    x=1,y=1\quad\text{and }x =5,y=-3
    $$

1. Show that the following hyperbolic identity holds:
    $$\cosh^2(x)-\sinh^2(x)=1.$$

Answer:
Use the definitions of $\cosh(x) = \frac{e^x + e^-x}{2}$ and $\sinh(x) = \frac{e^x - e^{-x}}{2}$
$$
\begin{align}
\cosh^2(x) - \sinh^2(x) &=(\cosh(x) + \sinh{x})(\cosh(x) - \sinh(x))\\
&=\left(\frac{e^x + e^{-x} + e^x - e^{-x}}{2}\right)\left(\frac{e^x + e^{-x} - e^x + e^{-x}}{2}\right)\\
&=e^x e^{-x}\\
&= 1 \text{ as required}
\end{align}
$$

1. Use natural logarthims to make $t$ the subject of the formula
    $$V=1-e^{\frac{-t}{RC}}.$$

Answer:
Make the exponential term the subject and then take the natural logarithms of both sides
$$
\begin{align}
V &= 1- e^{\frac{-t}{RC}}\\
e^{\frac{-t}{RC}} &= 1- v\\
\ln\left(e^{\frac{-t}{RC}}\right) &= \ln(1- v)\\
\frac{-t}{RC} &= \ln(1-v)\\
t &= -RC\ln(1-v)
\end{align}
$$

1. Find the solutions to the following equations without using a calculator.
    a. $x=\log_4(64)$
    a. $x=\log_{101}(101)$
    a. $x=\ln(e)$
    a. $x=\log_{56}(1)$
    a. $10^x=100000$
    a. $2^x=128$
    a. $\log_3(x)=4$
    a. $\log_x(125)=3$
    
    
    Answers:
    a. $x = \log_4(64) = \log_4(4^3)=3$
    b. $x = \log_{101}(101) =\log_{101}(101^1)=1$
    c. $x = \ln(e) =\log_e(e^1)= 1$
    d. $x = log_{56}(1) =\log_{56}(56^0)=0$
    e. $10^x = 100000=10^5 \Rightarrow x = 5$
    f. $2^x = 128=2^7$ \Rightarrow x = 7$ the powers of 2 are useful to know
    g. $3^{\log_3(x)} = 3^4 \Rightarrow x = 3^4 = 3^2 \times 3^2 = 81$
    h. $\log_x(125) = 3 \Rightarrow x^3 = 125 \Rightarrow x = 5$


1. Calculate the following logarithms using a calculator.
    a. $\ln(2)$
    a. $\log(20)$
    a. $\log_{16}(100)$ - do this using your $\log_a(x)$ button and also using the change of base rule with your $\log$ or $\ln$ button.

    Answers:
    To 2 d.p.
    a. $\ln(2) = 0.69$
    b. $\log(20) = 1.30$
    c. $\log_{16}(100) = 1.66$ or using the change of base rule with $\log_{10}$, $\log_{16}=\frac{\log_{10}(100)}{\log_{10}(16)}=\frac{2}{\log_{10}(16)}=1.66$

1. Calculate $4321\times 9876$ using logs: convert both values to logs, add, then convert back.

Answer:
$$\log(4321 \times 9876)=\log(4321) + \log(9876) = 7.630165..., \text{ the product rule of logarithms}\\
4321 \times 9876=10^{7.630165...} = 42674196
$$

1. Simplify the following expression involving logarithms.
     $$\log_a(x^2)+3\log_a(x)-2\log_a(4x^2).$$

Answer:
Applying the various log rules, starting with the power rules then product and quotient rules:
$$
\begin{aligned}
& \log_a(x^2)+3\log_a(x)-2\log_a(4x^2)\\
&= \log_a(x^2) + \log_a(x^3) - log_a(16x^4)\\
&= \log_a(\frac{x^5}{16x^4})\\
&= \log_a(\frac{x}{16})
\end{aligned}
$$


1. Solve the following for $x$.
    $$2\log_a(x)-\log_a(x-1)=\log_a(x+3).$$

Answer:
$$
\begin{aligned}
2 \log_a(x) - \log_a(x-1) &= \log_a(x+3)\\
\log_a\left(\frac{x^2}{x-1}\right) &= \log_a(x+3)\\
\log_a\left(\frac{x^2}{(x-1)(x+3)}\right) &= 0, \text{ since } \log_a(1) = 0\\
\frac{x^2}{(x-1)(x+3)} &= 1\\
x^2 &= (x-1)(x+3) = x^2 + 2x - 3\\
x &= \frac{3}{2}
\end{aligned}
$$

1. Solve the following for $x$.
    $$\log_a(x^2-10)-\log_a(x)=2\log_a(3).$$

Answer:
$$
\begin{align}
\log_a(x^2-10)-\log_a(x)&=2\log_a(3)\\
\log_a(x^2-10) &= \log_a(x) + \log_a(3^2)\\
\log_a(x^2-10) &= \log_a(9x)\\
x^2-10&=9x\\
x^2-9x-10&=0\\
(x+1)(x-10)&=0\\
\end{align}
$$
Hence $x=-1$ or $x=10$.

1. Bacteria are undergoing cell division every 30 minutes. Approximating the number of bacteria as a continuous variable $x$, if there are initially 5 bacteria, write an equation for the number of bacteria $x$ at time $t$ in the form
$$x=A2^{kt}$$
where $t$ is measured in minutes.
Also express this in the form
$$x=Ae^{\lambda t}$$
by finding the appropriate value of $\lambda$.

Answers:
Since $t$ is in minutes and the bacteria double every 30 mins, we have
$$x=A2^{\frac{1}{30}t}.$$
At the initial time $t=0$
$$x=A2^{\frac{1}{30}\times 0}=A2^0=A\times 1=A$$
hence $A=5$ and we have
$$x=5\times2^{\frac{1}{30}t}.$$

We can write $2^{\frac{1}{30}t}=(2^{\frac{1}{30}})^t$ and hence $\lambda=\ln(2^{\frac{1}{30}})=\frac{\ln(2)}{30}$. Then
$$x=5e^{\frac{\ln(2)}{30}t}.$$

1. A quantity $x$ is increasing exponentially with respect to time $t$. We have the measurements $x=21$ at $t=0$ and $x=156$ at $t=10$. Find an equation for $x$ in the form $x=Ae^{kt}$.

Answers:
At $t=0$
$$x=Ae^{k\times0}=A\times 1=21$$
so $A=21$.

At $t=10$
$$x=21e^{k\times 10}=156.$$
Taking natural logs
$$\ln(21e^{10k})=\ln(21)+10k=\ln(156)$$
hence
$$k=\frac{1}{10}\left(\ln(\frac{156}{21})\right)=0.20 (2 d.p.)$$.
Then
$$x=21e^{0.2t}.$$

1. The number of specimens of an invasive plant species is observed to be increasing at a particular location. The number of plants observed last year was $N=52$ and this year is $N=76$. We shall approximate the number of plants as a continuous variable $x$.

    a. Assuming continuous exponential growth $x=Ae^{\lambda t}$, find the growth rate $\lambda$.
    b. Approxiately how many plants are predicted by this model after 10 years from now?

Answer:

a. We can take last year as the starting time $t=0$, so that $x=Ae^{\lambda\times 0}=A=52$. Then taking time in units of years, we have
$$x=52e^{\lambda\times 1}=76.$$
Taking natural logs of both sides,
$$\ln(52)+\lambda=\ln(76)$$
Hence
$$\lambda = \ln\left(\frac{76}{52}\right)=0.38 (2 d.p.)$$

b. 10 years from now corresponds to $t=11$, so we have
$$x=52e^{0.38\times 11}\approx 3380 \text{ plants}.$$
    

1. Solve the following inequalities.

    a.  $7-3x>x-5$
    b.  $x^2\ge 4$
    c.  $x^2-x-6<0$
    d.  $x^2-3x-12\le 2x+2$
    e.  $\frac{2}{2x-1} > \frac{3}{3x+1}$
    f.  $\frac{2x}{x-5}\le 3$
    g.  $x^3-9x^2<0$


    Answers:
    a.
    \begin{align*}
    7-3x  &> x-5\\
    13  &> 4x\\
    x  &< \frac{13}{4}
    \end{align*}

    
    b. Here, we must include both the positive and the negative solution to the square root:
    \begin{align*}
    x^2 &\geq 4\\
    \pm x &\geq 2\\
    x\geq 2 & x\leq -2
    \end{align*}
    It is often worth sketching the graph and examining the inequality to determine where the inequality is satisfied.
    
    c.
    $$
    x^2 - x - 6 < 0 \\
    (x+2)(x-3) < 0
    $$
    The graph of $x^2$ will form a $\cup$ shape, so the parts below the axis are between the crossing points of $x = -2$ and $x=3$. So the inequality is satisfied for
    $$
    -2<x<3
    $$
    Note the use of strict inequalities $x<3$ and $x>-2$ because the inequality is $<0$ (as opposed to $\leq$).

    d. Group terms to form a quadratic, find the solutions and determine whether the interval between them or outside of them satisfied the inequality:
    \begin{align*}
    x ^2 - 3x - 12 &\leq 2x + 2\\
    x^2 - 5x - 14 &\leq 0\\
    (x-7)(x+2)&\leq 0
    \end{align*}
    And the part of the curve below the axis is the range $-2\leq x \leq 7$
  
e. Do not multiply through by a variable, since at times the term will be negative and necessitate a flip of the inequality. Instead, subtract one side from both sides:

    \begin{align*}
    \frac{2}{2x-1} &> \frac{3}{3x+1}\\
    \frac{2}{2x-2} - \frac{3}{3x+1} &> 0\\
    \frac{2(3x+1) - 3(2x-1)}{(2x-1)(3x+1)} &> 0\\
    \frac{5}{(2x-1)(3x+1)} &> 0
    \end{align*}

    In order for the inequality to hold, either both terms in the denominator are positive or both are negative.
    $$
    \text{positve case: }2x-1>0,\quad 3x+1 > 0\\
    x > \frac{1}{2} \text{ and } x > \frac{1}{3}\\
    x > \frac{1}{2}\\
    \text{negative case: }2x-2 < 0, \quad 3x+1 < 0\\
    x<\frac{1}{2} \text{ and } x < \frac{1}{3}\\
    x < \frac{1}{3}
    $$
    So the final solution is $x > \frac{1}{2}$ and $x < \frac{1}{3}$.

    f.
    \begin{align*}
    \frac{2x}{x-5} &\leq 3 \\
    \frac{2x}{x-5} - 3 &\leq 0\\
    \frac{2x - 3(x-5)}{x-5} & \leq 0\\
    \frac{15-x}{x-5}&\leq 0
    \end{align*}

    Which will ony old if one of the numerator or denominator is negative. So the inequality is solved by $x\geq 15$ and $x\leq 5$.

    g.
    Here, a cubic is presented, but a factor of $x^2$ can be taken out
    \begin{align*}
    x^3 - 9x^2 &< 0 \\
    x^2(x-9) &< 0\\
    \end{align*}
    The $x^2$ factor is always positive, so the whole inequality holds when $x-9$ is negative. Hence, $x<9$
